### ISSUE TITLE
Original Scraping files

### ISSUE THREAD

**Issue by luc-kalaora** [TheophileBlard/french-sentiment-analysis-with-bert#35]
Hi
I will be interested by your allocine scraping files  (reviews ratings between 0 to 5) . Could you share me .pickle files that compile all the extracted data. It will be very helpful.
Thanks in advance

**Comment by TheophileBlard** [comment]
> Hi
> I will be interested by your allocine scraping files  (reviews ratings between 0 to 5) . Could you share me .pickle files that compile all the extracted data. It will be very helpful.
> Thanks in advance

Hi! I'm sorry but I don't have the original pickle files anymore. But you can try to regenerate a newer version of the dataset with the code of the repo !

**Comment by luc-kalaora** [comment]
Thanks for your response.
