### ISSUE TITLE
Prediction scores

### ISSUE THREAD

**Issue by TheophileBlard** [TheophileBlard/french-sentiment-analysis-with-bert#4]
With [🤗Transformers pipelines](https://huggingface.co/transformers/main_classes/pipelines.html) it's very easy to get prediction scores, for each class.

> Bonjour, 
Ma question se repose sur le code que vous avez utilisé pour calculer le pourcentage ( score) pour chaque sentiment (positive et negative), je le trouve pas sur votre page de github , le résultat d'affichage que je parle est montré sur cette page : https://huggingface.co/tblard/tf-allocine?text=Je+t%27appr%C3%A9cie+beaucoup.+Je+t%27aime.
Pour moi, je veux exécuter ce code sur mon propre script et pas seulement tester le résultat sur le site. 
Pouvez vous svp de l'ajouter sur votre page github ou de me l'envoyer directement sur ma boite email: abzdhouda@gmail.com.
Merci pour votre aide.

_Originally posted by @hodhoda in https://github.com/TheophileBlard/french-sentiment-analysis-with-bert/issues/3#issuecomment-748099684_

## 1. First instantiate Tokenizer & Model
```python
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
from transformers import pipeline

tokenizer = AutoTokenizer.from_pretrained("tblard/tf-allocine")
model = TFAutoModelForSequenceClassification.from_pretrained("tblard/tf-allocine")
```

## 2. Then create pipeline
Do not forget to set the `return_all_scores` parameter to `True`, otherwise the pipeline will only output the probability of the predicted class.
```python
nlp = pipeline('sentiment-analysis', model=model, tokenizer=tokenizer, return_all_scores=True)
```

## 3. Last, feed the pipeline
```python
result = nlp("J'aime le camembert")
result
```
```sh
[[{'label': 'NEGATIVE', 'score': 0.21667276322841644},
  {'label': 'POSITIVE', 'score': 0.7833272218704224}]]
```

**Comment by diamondspark** [comment]
@TheophileBlard Thank you for your work. I would like to bypass "pipeline". Where do I get your trained sentiment model?
