### ISSUE TITLE
Can we set the pipfile to use python 3.7 or is it necessary to have python 3.8 install ?

### ISSUE THREAD

**Issue by keloemma** [TheophileBlard/french-sentiment-analysis-with-bert#7]
Hello, 
as the title suggests , i am trying to run your conda on my computer and I was wondering if I could set up the version of python to 3.7 or is it necessary to have 3.8 ?

**Comment by TheophileBlard** [comment]
I don't think python 3.8 is a hard dependency of the project, thus I believe 3.7 should work. Let me know if something goes wrong !

**Comment by TheophileBlard** [comment]
Hi @keloemma, did you succeed setting up the project with python 3.7 ?
